--- a/arch/arm/dts/Makefile
+++ b/arch/arm/dts/Makefile
@@ -1191,6 +1191,7 @@ dtb-$(CONFIG_TARGET_HAILO12L_VELOCE) += hailo12l-veloce.dtb
 dtb-$(CONFIG_TARGET_HAILO12L_MINT) += hailo12l-mint.dtb
 dtb-$(CONFIG_TARGET_HAILO12L_MAPLE) += hailo12l-maple.dtb
+dtb-$(CONFIG_TARGET_ASTRIAL_H15) += astrial-h15.dtb
 
 targets += $(dtb-y)
