name: Test Release Creation

on:
  push:
    branches:
      - github-release
  workflow_dispatch:
    inputs:
      source_run_id:
        description: 'Source workflow run ID to get artifacts from'
        required: true
        default: '16664972453'

jobs:
  test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts from Existing Run
        uses: dawidd6/action-download-artifact@v3
        with:
          name: astrial-h15-yocto-build
          path: ./release-files
          run_id: ${{ inputs.source_run_id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Compressed Release Archive
        run: |
          cd release-files
          zip -r ../astrial-h15-yocto-build-test-v${{ github.run_number }}.zip .
          cd ..
          ls -lh astrial-h15-yocto-build-test-v${{ github.run_number }}.zip

      - name: Create Test Release with Compressed Archive
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test-v${{ github.run_number }}
          name: Test Release v${{ github.run_number }}
          body: |
            **Test Release - Build Information:**
            - Branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
            - Source artifacts from run: ${{ inputs.source_run_id }}
            - Build Date: ${{ github.event.head_commit.timestamp }}
            
            **Download and extract astrial-h15-yocto-build-test-v${{ github.run_number }}.zip to get:**
            - `core-image-hailo-dev-astrial-h15.wic`: Full development image
            - `core-image-minimal-astrial-h15.wic`: Minimal image
            - `fitImage-astrial-h15.bin`: Kernel and device tree
            - `hailo15_uart_recovery_fw.bin`: UART recovery firmware
            - `hailo15_scu_bl.bin`: SCU bootloader
            - `scu_bl_cfg_a.bin`: SCU bootloader configuration
            - `hailo15_scu_fw.bin`: SCU firmware
            - `u-boot.dtb.signed`: Signed U-Boot device tree
            - `u-boot-spl.bin`: U-Boot SPL
            - `u-boot-initial-env`: U-Boot initial environment
            - `customer_certificate.bin`: Customer certificate
            - `u-boot-tfa.itb`: U-Boot TFA
          files: astrial-h15-yocto-build-test-v${{ github.run_number }}.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
